name: housesolutions
description: House Solutions Majikan.

version: 1.4.17+52

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc_pattern: ^2.5.1
  rxdart: ^0.22.6
  font_awesome_flutter: ^8.5.0
  shared_preferences: ^0.5.6
  http: ^0.12.0+2
  url_launcher: ^5.4.0
  firebase_messaging: ^6.0.7
  google_sign_in: ^4.1.0
  flutter_facebook_login: ^3.0.0
  indonesia: ^1.0.1
  package_info: ^0.4.0+13
  flutter_local_notifications: ^0.8.4+3
  cryptoutils: ^0.4.0
  carousel_slider: ^1.3.1
  cached_network_image: ^1.1.3
  flutter_html: ^0.11.0
  device_id: ^0.2.0
  date_format: ^1.0.8
  image_picker: ^0.6.2+3
  intro_slider: ^2.2.8
  flutter_rating_bar: ^3.0.0
  flutter_alert: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: ^0.7.4
  flutter_app_host: ^0.2.2

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/Images/icon.png"


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - locale/i18n_en.json
    - locale/i18n_id.json
    #assets-generator-begin
    #assets/Images/*
    - assets/Images/01.png
    - assets/Images/02.png
    - assets/Images/03.png
    - assets/Images/1.png
    - assets/Images/2.png
    - assets/Images/3.png
    - assets/Images/4.png
    - assets/Images/5.png
    - assets/Images/bca.png
    - assets/Images/bri.png
    - assets/Images/customer.png
    - assets/Images/empty_transaction.png
    - assets/Images/empty_worker.png
    - assets/Images/en.png
    - assets/Images/eror.png
    - assets/Images/garansi.png
    - assets/Images/icon.png
    - assets/Images/id.png
    - assets/Images/logo.png
    - assets/Images/mandiri.png
    - assets/Images/not_found.png
    - assets/Images/other.png
    - assets/Images/worker.png
    - assets/Images/worker_animation.png
    #assets-generator-end
