name: housesolutions
description: House Solutions Majikan.

version: 1.7.6+72

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc_pattern: ^2.5.1
  rxdart: ^0.22.6
  font_awesome_flutter: ^8.5.0
  shared_preferences: ^0.5.6
  http: ^0.12.0+2
  url_launcher: ^5.4.0
  firebase_messaging: ^6.0.7
  google_sign_in: ^4.1.0
  flutter_facebook_login: ^3.0.0
  indonesia: ^1.0.1
  package_info: ^0.4.0+13
  flutter_local_notifications: ^0.8.4+3
  cryptoutils: ^0.4.0
  carousel_slider: ^1.3.1
  cached_network_image: ^2.0.0-rc.1
  flutter_html: ^0.11.0
  device_id: ^0.2.0
  date_format: ^1.0.8
  image_picker: ^0.6.2+3
  intro_slider: ^2.2.8
  flutter_rating_bar: ^3.0.0
  flutter_alert: ^0.4.0
  responsive_screen: ^1.0.0
  flutter_full_pdf_viewer: ^1.0.6
  path_provider: ^1.5.1
  lazy_load_scrollview: ^1.0.1
  # flutrans: ^0.0.4
  lazy_load_refresh_indicator: ^1.0.0+1
  clippy_flutter: ^1.1.0
  flutter_secure_storage: ^3.3.1+1
  badges: ^1.1.1
  firebase_auth: ^0.15.5+2
  firebase_database: ^3.1.3
  streaming_shared_preferences: ^1.0.1
  photo_view: ^0.9.2


dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: ^0.7.4
  flutter_app_host: ^0.2.2

flutter_icons:
  android: "ic_launcher" 
  ios: true
  image_path: "assets/Images/icon.png"


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - locale/i18n_en.json
    - locale/i18n_id.json
    #assets-generator-begin
    #assets/Images/*
    - assets/Images/01.png
    - assets/Images/02.png
    - assets/Images/03.png
    - assets/Images/1.png
    - assets/Images/2.png
    - assets/Images/3.png
    - assets/Images/4.png
    - assets/Images/5.png
    - assets/Images/background.png
    - assets/Images/banner_1.png
    - assets/Images/banner_2.png
    - assets/Images/banner_3.png
    - assets/Images/banner_online.png
    - assets/Images/banner_pp.png
    - assets/Images/banner_regular.png
    - assets/Images/bca.png
    - assets/Images/belum_memiliki_pekerja.png
    - assets/Images/belum_memiliki_transaksi.png
    - assets/Images/bri.png
    - assets/Images/cancel.png
    - assets/Images/chat.png
    - assets/Images/checklist.png
    - assets/Images/customer.png
    - assets/Images/data_tidak_tersedia.png
    - assets/Images/empty_transaction.png
    - assets/Images/empty_worker.png
    - assets/Images/en.png
    - assets/Images/eror.png
    - assets/Images/family.png
    - assets/Images/foto_diri.png
    - assets/Images/garansi.png
    - assets/Images/header.png
    - assets/Images/healty.png
    - assets/Images/home_1.jpg
    - assets/Images/home_2.jpg
    - assets/Images/icon.png
    - assets/Images/icon_1.png
    - assets/Images/icon_aktif.png
    - assets/Images/icon_foto.png
    - assets/Images/icon_izin_kel.png
    - assets/Images/icon_kk.png
    - assets/Images/icon_ktp.png
    - assets/Images/icon_rtrw.png
    - assets/Images/icon_siapkandoc.png
    - assets/Images/icon_skck.png
    - assets/Images/icon_vical.png
    - assets/Images/id.png
    - assets/Images/job_inform.png
    - assets/Images/kitchen.png
    - assets/Images/logo.png
    - assets/Images/logo_fix.png
    - assets/Images/logo_white.png
    - assets/Images/mandiri.png
    - assets/Images/midtrans.png
    - assets/Images/news.png
    - assets/Images/not_found.png
    - assets/Images/notification.png
    - assets/Images/offline.png
    - assets/Images/online.png
    - assets/Images/other.png
    - assets/Images/pinger_print.png
    - assets/Images/pp.png
    - assets/Images/regular.png
    - assets/Images/terjadi_kesalahan.png
    - assets/Images/tf.png
    - assets/Images/underconstruction_chat.png
    - assets/Images/worker.png
    - assets/Images/worker_animation.png
    #assets-generator-end
